force-app/main/default/objects/Employee_Leave_Balance__c/Employee_Leave_Balance__c.object-meta.xml
<CustomObject>
    <label>Employee Leave Balance</label>
    <nameField>
        <label>Employee Leave Balance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Leave Balance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Leave_Balance__c/fields/Leave__c.field-meta.xml
<CustomField>
    <fullName>Leave__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leave</label>
    <referenceTo>Leave__c</referenceTo>
    <relationshipLabel>Employee Leave Balance</relationshipLabel>
    <relationshipName>Employee_Leave_Balance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Balance__c/fields/Leave_Accured_So_Far__c.field-meta.xml
<CustomField>
    <fullName>Leave_Accured_So_Far__c</fullName>
    <label>Leave Accured So Far</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Balance__c/fields/Leave_Annual_Quota__c.field-meta.xml
<CustomField>
    <fullName>Leave_Annual_Quota__c</fullName>
    <label>Leave Annual Quota</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Balance__c/fields/Leave_Available__c.field-meta.xml
<CustomField>
    <fullName>Leave_Available__c</fullName>
    <label>Leave Available</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Balance__c/fields/Leave_Carryover__c.field-meta.xml
<CustomField>
    <fullName>Leave_Carryover__c</fullName>
    <label>Leave Carryover</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Leave_Balance__c/fields/Leave_Consumed__c.field-meta.xml
<CustomField>
    <fullName>Leave_Consumed__c</fullName>
    <label>Leave Consumed</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave__c/Leave__c.object-meta.xml
<CustomObject>
    <label>Leave</label>
    <nameField>
        <label>Leave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EmployeeLeaveController.cls
public with sharing class EmployeeLeaveController {
    @AuraEnabled
    public static List<Employee_Leave_Balance__c> getLeaveBalances(){
        try {
            List<Employee_Leave_Balance__c> myLeaves = new List<Employee_Leave_Balance__c>();
            myLeaves = [SELECT Id, Name, Leave__r.Name, Leave_Accured_So_Far__c, Leave_Annual_Quota__c, Leave_Available__c, Leave_Carryover__c, Leave_Consumed__c FROM Employee_Leave_Balance__c WITH SECURITY_ENFORCED];
            return myLeaves;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}